---
title: "Multilevel Simple"
author: "Tin Oreskovic"
date: "11/25/2018"
output:
  html_document:
    df_print: paged
  pdf_document:
    fig_caption: yes
    keep_tex: yes
  word_document: default
---



```{r setup, include=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

```{r}
#install.packages("ggplot2")
#install.packages("tidyquant")
#install.packages("rstanarm")
#install.packages("lme4")
#install.packages("stringr")
#install.packages("genderdata_package")
#install.packages("gender")
#install.packages("shiny")
#install.packages('tidyr')
#install.packages('dplyr')
#install.packages("car")
#install.packages("merTools")
#install.packages("sjPlot")
```



```{r}
library(ggplot2)
library(scales)
library(ggthemes)
library(dplyr)
library(plyr)
library(arm)
library(rstanarm)
library(lme4)
library(HLMdiag)
library(car)
library(merTools)  
```

```{r}
generic <- read.csv('~/Desktop/capstone/all_generic_with_districts.csv')

specific <- read.csv('~/Desktop/capstone/all_specific.csv')

```


```{r}
library(tidyr)      
generic <- separate(data = generic, col = district, into = c("state", "district"), sep = "\\-")
specific <- separate(data = specific, col = district, into = c("state", "district"), sep = "\\-")
generic <- within(generic,  district <- paste(state, district, sep="-"))
specific <- within(specific,  district <- paste(state, district, sep="-"))
```

```{r}
generic <- subset(generic, vote2018 != "Other candidate/not sure")
specific <- subset(specific, vote2018 != "Other candidate/not sure")
generic <- subset(generic, vote2018 != "Will not vote")
specific <- subset(specific, vote2018 != "Will not vote")
```



```{r}
intercept_fit_specific <- glmer(vote2018 ~ age + urbanicity + gender + race + education + party + married + (1 | state/district), data = specific, family = binomial(link = "logit"))

```

```{r}
intercept_fit_generic <- glmer(vote2018 ~ age + urbanicity + gender + race + education + party + married + (1 | state/district), data = generic, family = binomial(link = "logit"))

```


```{r}
display(intercept_fit_specific)
```

```{r fig.height=9, fig.width=15}
display(intercept_fit_generic)
```

```{r fig.height=12, fig.width=15}
require(lattice)
#dotplot(ranef(intercept_fit_specific, condVar=TRUE))
```

```{r fig.height=30, fig.width=15}
require(lattice)
#dotplot(ranef(intercept_fit_generic, condVar=TRUE))
```


The plots below show the simulated random effects. Estimates distinguishable from zero based on the 
the confidence band are highlighted. 



```{r fig.height=9, fig.width=15}
randoms_specific_intercept <- REsim(intercept_fit_specific, n.sims = 500)
plotREsim(randoms_specific_intercept) + theme_light(base_size = 26) 
```

```{r fig.height=9, fig.width=15}
randoms_generic_intercept <- REsim(intercept_fit_generic, n.sims = 500)
plotREsim(randoms_generic_intercept) + theme_light(base_size = 26) 
```


```{r}
specific$fitted_spec <- fitted(intercept_fit_specific)
specific$resid_spec <- resid(intercept_fit_specific)  
```


```{r}
generic$fitted_gen <- fitted(intercept_fit_generic)
generic$resid_gen <- resid(intercept_fit_generic)  

```



```{r fig.height=9, fig.width=12}
binnedplot(specific$fitted_spec, specific$resid_spec)
```



```{r fig.height=9, fig.width=12}
binnedplot(generic$fitted_gen, generic$resid_gen)
```

















```{r}
#install.packages("optimx")
library("optimx")
```


```{r}
slopes_fit_generic2 <- glmer(vote2018 ~ age + urbanicity + gender + race + education + married + party + (1 + gender | state/district), data = generic, family = binomial(link = "logit"),
     control = lmerControl(optimizer = "optimx", calc.derivs = FALSE,
     optCtrl = list(method = "nlminb", starttests = FALSE, kkt = FALSE)))
```



```{r}
slopes_fit_specific2 <- glmer(vote2018 ~ age + urbanicity + gender + race + education + married + party + (1 + gender | state/district), data = specific, family = binomial(link = "logit"),
     control = lmerControl(optimizer = "optimx", calc.derivs = FALSE,
     optCtrl = list(method = "nlminb", starttests = FALSE, kkt = FALSE)))

```


```{r}
display(slopes_fit_specific2)
```



```{r}
display(slopes_fit_generic2)
```




```{r fig.height=9, fig.width=15}
randoms_specific_slopes <- REsim(slopes_fit_specific2, n.sims = 500)
plotREsim(randoms_specific_slopes) + theme_light(base_size = 26) 
```

```{r fig.height=9, fig.width=15}
randoms_generic_slopes <- REsim(slopes_fit_generic2, n.sims = 500)
plotREsim(randoms_generic_slopes) + theme_light(base_size = 26) 
```




```{r}
specific$fitted_spec_slope <- fitted(slopes_fit_specific2)
specific$resid_spec_slope <- resid(slopes_fit_specific2)  
```


```{r}
generic$fitted_gen_slope <- fitted(slopes_fit_generic2)
generic$resid_gen_slope <- resid(slopes_fit_generic2)  

```


```{r fig.height=9, fig.width=15}
require(lattice)
#dotplot(ranef(slopes_fit_specific2, condVar=TRUE))
```



```{r fig.height=100, fig.width=15}
require(lattice)
#dotplot(ranef(slopes_fit_generic2, condVar=TRUE))
```



```{r fig.height=9, fig.width=12}
binnedplot(specific$fitted_spec_slope, specific$resid_spec_slope)
```



```{r fig.height=9, fig.width=12}
binnedplot(generic$fitted_gen_slope, generic$resid_gen_slope)
```



```{r}
slopes_fit_generic3 <- glmer(vote2018 ~ age + urbanicity + gender + race + education + married + party + (1 + gender | state/district), data = generic, family = binomial(link = "logit"),
     control = lmerControl(optimizer = "optimx", calc.derivs = FALSE,
     optCtrl = list(method = "nlminb", starttests = FALSE, kkt = FALSE)))
```



```{r}
slopes_fit_specific3 <- glmer(vote2018 ~ age + urbanicity + gender + race + education + party + (1 + gender | state/district), data = specific, family = binomial(link = "logit"),
     control = lmerControl(optimizer = "optimx", calc.derivs = FALSE,
     optCtrl = list(method = "nlminb", starttests = FALSE, kkt = FALSE)))

```



```{r}
slopes_fit_generic3 <- glmer(vote2018 ~ age + urbanicity + gender + race + education + party + age*gender + (1 + gender + age | state/district), data = generic, family = binomial(link = "logit"),
     control = lmerControl(optimizer = "optimx", calc.derivs = FALSE,
     optCtrl = list(method = "nlminb", starttests = FALSE, kkt = FALSE)))
```



```{r}
slopes_fit_specific3 <- glmer(vote2018 ~ age + urbanicity + gender + race + education + party + age*gender + (1 + gender + age | state/district), data = specific, family = binomial(link = "logit"),
     control = lmerControl(optimizer = "optimx", calc.derivs = FALSE,
     optCtrl = list(method = "nlminb", starttests = FALSE, kkt = FALSE)))

```


```{r}
display(slopes_fit_specific3)
```



```{r}
display(slopes_fit_generic3)
```

```{r}
specific$fitted_spec_slope3 <- fitted(slopes_fit_specific3)
specific$resid_spec_slope3 <- resid(slopes_fit_specific3)  
```

```{r}
generic$fitted_gen_slope3 <- fitted(slopes_fit_generic3)
generic$resid_gen_slope3 <- resid(slopes_fit_generic3)  
```



```{r fig.height=9, fig.width=12}
binnedplot(specific$fitted_spec_slope3, specific$resid_spec_slope3)
```



```{r fig.height=9, fig.width=12}
binnedplot(generic$fitted_gen_slope3, generic$resid_gen_slope3)
```



```{r fig.height=20, fig.width=15}
randoms_gspecific_slopes3 <- REsim(slopes_fit_specific3, n.sims = 500)
plotREsim(randoms_gspecific_slopes3) + theme_light(base_size = 26) 
```



```{r fig.height=20, fig.width=15}
randoms_generic_slopes3 <- REsim(slopes_fit_generic3, n.sims = 500)
plotREsim(randoms_generic_slopes3) + theme_light(base_size = 26) 
```


